In [2]:
import numpy as np
from scipy.sparse.linalg import svds

# Пример бинарной матрицы взаимодействия
R = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1],
              [1, 1, 0, 0],
              [0, 0, 1, 1]]).astype(float)

# Задаем количество латентных факторов
k = 2

# Применяем SVD
U, sigma, Vt = svds(R, k=k)
sigma = np.diag(sigma)

# Восстанавливаем матрицу предсказаний
predicted_ratings = np.dot(np.dot(U, sigma), Vt)

# Округление для интерпретации как вероятностей
recommendations = (predicted_ratings > 0.5).astype(int)
print("Матрица рекомендаций:\n", recommendations)


Матрица рекомендаций:
 [[1 0 1 0]
 [0 1 0 1]
 [0 1 0 1]
 [1 0 1 0]]
